export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";

export const REPORT_START = "REPORT_START";
export const REPORT_SUCCESS = "REPORT_SUCCESS";
export const REPORT_FAIL = "REPORT_FAIL";
export const REPORT_LIST_SUCCESS = "REPORT_LIST_SUCCESS";

export const TOP_USERS_START = "TOP_USERS_START";
export const TOP_USERS_SUCCESS = "TOP_USERS_SUCCESS";
export const TOP_USERS_FAIL = "TOP_USERS_FAIL";