export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";

export const REPORT_START = "REPORT_START";
export const REPORT_SUCCESS = "REPORT_SUCCESS";
export const REPORT_FAIL = "REPORT_FAIL";
export const REPORT_LIST_SUCCESS = "REPORT_LIST_SUCCESS";

export const TOP_USERS_START = "TOP_USERS_START";
export const TOP_USERS_SUCCESS = "TOP_USERS_SUCCESS";
export const TOP_USERS_FAIL = "TOP_USERS_FAIL";


export const FETCH_ALL_USERS_REQUEST = "FETCH_ALL_USERS_REQUEST";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILURE = "FETCH_ALL_USERS_FAILURE";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
export const UPDATE_USER_ROLE_REQUEST = "UPDATE_USER_ROLE_REQUEST";
export const UPDATE_USER_ROLE_SUCCESS = "UPDATE_USER_ROLE_SUCCESS";
export const UPDATE_USER_ROLE_FAILURE = "UPDATE_USER_ROLE_FAILURE";
export const FETCH_REPORTS_REQUEST = "FETCH_REPORTS_REQUEST";
export const FETCH_REPORTS_SUCCESS = "FETCH_REPORTS_SUCCESS";
export const FETCH_REPORTS_FAILURE = "FETCH_REPORTS_FAILURE";
export const VERIFY_REPORT_REQUEST = "VERIFY_REPORT_REQUEST";
export const VERIFY_REPORT_SUCCESS = "VERIFY_REPORT_SUCCESS";
export const VERIFY_REPORT_FAILURE = "VERIFY_REPORT_FAILURE";
export const REJECT_REPORT_REQUEST = "REJECT_REPORT_REQUEST";
export const REJECT_REPORT_SUCCESS = "REJECT_REPORT_SUCCESS";
export const REJECT_REPORT_FAILURE = "REJECT_REPORT_FAILURE";

export const PREDICT_START = "PREDICT_START";
export const PREDICT_SUCCESS = "PREDICT_SUCCESS";
export const PREDICT_FAIL = "PREDICT_FAIL";

export const SET_USER_COUNT = "SET_USER_COUNT";
export const SET_ALL_REQUESTS = "SET_ALL_REQUESTS";